### ISSUE TITLE
Doesn´t seem to work with several rss-feeds

### ISSUE THREAD

**Issue by vincentmakayama** [putuwahyu29/feednews#3]
Doesn´t seem to work with several rss-feeds
For example:

https://feeds.nos.nl/nosnieuwsalgemeen

or

https://www.crimesite.nl/feed/

What could be the cause?

**Comment by putuwahyu29** [comment]
Check cors. Check console on browser

**Comment by vincentmakayama** [comment]
Thanks for your reaction. It was indeed a CORS issue. 
I tried a workaround, using https://cors-anywhere.herokuapp.com/

However, I´m still getting an error with the NOS feed:

script.js:18 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'childNodes')
    at displayFeedList (script.js:18:65)
    at script.js:8:7
displayFeedList @ script.js:18
(anonymous) @ script.js:8

Any idea what this could be?
